import{a as B,S as $,i as a}from"./assets/vendor-BK_rxH-O.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const F="51688063-4461a08693fd836abbdb4b603",P="https://pixabay.com/api/",h=15;async function m(o,e){const{data:s}=await B.get(P,{params:{key:F,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:h}});return s}const g=document.querySelector(".gallery"),L=document.querySelector(".load-more"),b=document.querySelector(".loader"),C=new $(".gallery a",{captionsData:"alt",captionDelay:250});function w(o){if(!o||o.length===0)return;const e=o.map(({webformatURL:s,largeImageURL:l,tags:t,likes:r,views:c,comments:q,downloads:_})=>`
      <li class="gallery__item">
        <a class="gallery__link" href="${l}">
          <img class="gallery__img" src="${s}" alt="${t}" />
          <div class="grid">
            <p>Likes</p><p>Views</p><p>Comments</p><p>Downloads</p>
            <span>${r}</span><span>${c}</span><span>${q}</span><span>${_}</span>
          </div>
        </a>
      </li>`).join("");g.insertAdjacentHTML("beforeend",e),C.refresh()}function A(){g.innerHTML=""}function S(){b.classList.remove("is-hidden")}function E(){b.classList.add("is-hidden")}function v(){L.classList.remove("is-hidden")}function p(){L.classList.add("is-hidden")}const f=document.querySelector(".form"),y=document.querySelector(".user-input"),M=document.querySelector(".load-more");let i=1,d="",u=0;const n={position:"topRight",messageColor:"#FAFAFB",messageSize:"16px",backgroundColor:"#EF4040",closeOnClick:!0,transitionIn:"bounceInLeft"};f.addEventListener("submit",async o=>{if(o.preventDefault(),d=y.value.trim(),!d){a.show({...n,message:"Please enter the search query"});return}i=1,u=0,p(),A(),S();try{const e=await m(d,i);if(u=e.totalHits||0,!e.hits||e.hits.length===0){a.show({...n,message:"Sorry, there are no images matching your search query. Please try again!"});return}w(e.hits),i*h<u?v():(p(),a.show({...n,backgroundColor:"#4E75FF",message:"We're sorry, but you've reached the end of search results."}))}catch(e){a.show({...n,message:`Sorry, an error happened. Try again. Error: ${e.message}`})}finally{E(),f.reset(),y.focus()}});M.addEventListener("click",async()=>{i+=1,p(),S();try{const o=await m(d,i);w(o.hits||[]);const e=document.querySelector(".gallery li");if(e){const{height:s}=e.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}i*h>=u?(p(),a.show({...n,backgroundColor:"#4E75FF",message:"We're sorry, but you've reached the end of search results."})):v()}catch(o){a.show({...n,message:`Sorry, an error happened. Try again. Error: ${o.message}`})}finally{E()}});
//# sourceMappingURL=index.js.map
